apiVersion: v1
kind: Pod
metadata:
  labels:
    app: logstash
  name: logstash
spec:
  containers:
  - image: opensearchproject/logstash-oss-with-opensearch-output-plugin:7.16.2
    name: logstash
    ports:
    - containerPort: 25826
    - containerPort: 5044
    env:
    - name: ES_HOSTS
      value: "http://localhost:5601"
    - name: ES_USER
      value: "admin"
    - name: ES_PASSWORD
      value: "y5J48vx80+9G"
    resources: {}
    volumeMounts:
    - name: config-volume
      mountPath: /usr/share/logstash/config
    - name: logstash-pipeline-volume
      mountPath: /usr/share/logstash/pipeline
  restartPolicy: OnFailure
  volumes:
  - name: config-volume
    configMap:
      name: logstash-configmap
      items:
        - key: logstash.yml
          path: logstash.yml
  - name: logstash-pipeline-volume
    configMap:
      name: logstash-configmap
      items:
        - key: logstash.conf
          path: logstash.conf
  # - name: cert-ca
  #   secret:
  #     secretName: elasticsearch-es-http-certs-public

status: {}